# Generated by Django 3.1.2 on 2020-10-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QeNoBiApp', '0002_auto_20201025_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='depth',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='period',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='support',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='item',
            field=models.CharField(default='test', max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
