# Generated by Django 3.1.2 on 2020-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QeNoBiApp', '0003_auto_20201025_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_source', models.CharField(default='test', max_length=30)),
                ('group_target', models.CharField(default='test', max_length=30)),
                ('user', models.CharField(default='test', max_length=30)),
            ],
        ),
    ]
